# Generated by Django 4.1.5 on 2023-01-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
