# Generated by Django 4.1.5 on 2023-02-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_curso_familiar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='dechaDeEntrega',
            new_name='fechaDeEntrega',
        ),
    ]
